//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrum_app.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sc_epica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sc_epica()
        {
            this.sc_historia_usuario = new HashSet<sc_historia_usuario>();
        }
    
        public long id_epica { get; set; }
        public string titulo { get; set; }
        public long fk_proyecto { get; set; }
        public string descricion { get; set; }
        public int fk_creado_por { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual sc_usuario sc_usuario { get; set; }
        public virtual sc_proyecto sc_proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sc_historia_usuario> sc_historia_usuario { get; set; }
    }
}
