//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrum_app.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sc_equipo
    {
        public int id_equipo { get; set; }
        public long fk_proyecto { get; set; }
        public int fk_usuario { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual sc_proyecto sc_proyecto { get; set; }
        public virtual sc_usuario sc_usuario { get; set; }
    }
}
