//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrum_app.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sc_spring
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sc_spring()
        {
            this.sc_spring_meeting = new HashSet<sc_spring_meeting>();
            this.sc_spring_backlog = new HashSet<sc_spring_backlog>();
        }
    
        public long id_spring { get; set; }
        public string nombre { get; set; }
        public int fk_creado_por { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public long fk_proyecto { get; set; }
        public int fk_estado_spring { get; set; }
    
        public virtual sc_estado_spring sc_estado_spring { get; set; }
        public virtual sc_proyecto sc_proyecto { get; set; }
        public virtual sc_usuario sc_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sc_spring_meeting> sc_spring_meeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sc_spring_backlog> sc_spring_backlog { get; set; }
    }
}
