//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrum_app.DB_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyecto_scrumEntities : DbContext
    {
        public proyecto_scrumEntities()
            : base("name=proyecto_scrumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sc_epica> sc_epica { get; set; }
        public virtual DbSet<sc_equipo> sc_equipo { get; set; }
        public virtual DbSet<sc_estado_historia_usuario> sc_estado_historia_usuario { get; set; }
        public virtual DbSet<sc_estado_proyecto> sc_estado_proyecto { get; set; }
        public virtual DbSet<sc_estado_spring> sc_estado_spring { get; set; }
        public virtual DbSet<sc_historia_usuario> sc_historia_usuario { get; set; }
        public virtual DbSet<sc_proyecto> sc_proyecto { get; set; }
        public virtual DbSet<sc_rol> sc_rol { get; set; }
        public virtual DbSet<sc_spring> sc_spring { get; set; }
        public virtual DbSet<sc_spring_backlog> sc_spring_backlog { get; set; }
        public virtual DbSet<sc_spring_meeting> sc_spring_meeting { get; set; }
        public virtual DbSet<sc_spring_meeting_type> sc_spring_meeting_type { get; set; }
        public virtual DbSet<sc_usuario> sc_usuario { get; set; }
    }
}
